dist: trusty

matrix:
  fast_finish: true

language: python

python:
  - 3.6
  - 2.7

install:
  - pip install -q flake8 coverage codecov

script:
  - "python -m coverage run -m unittest discover tests \"*_test.py\""
  - "python -m coverage xml"
  - "python -m flake8 wind"

after_success:
  - "codecov"
